"""bat runned migration

Revision ID: 638472071b22
Revises: 7c30ee3ab893
Create Date: 2020-09-24 05:17:19.135727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638472071b22'
down_revision = '7c30ee3ab893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
